### ISSUE TITLE
测试一下有个登录出错？

### ISSUE THREAD

**Issue by abanger** [kong36088/ZhihuSpider#1]
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>

{'remember_me': 'true', 'password': 'a123', '_xsrf': '2bfdaf95e7dfc204616bc031e7a8a222', 'email': 'e123r@qq.com'}
Traceback (most recent call last):
  File "/home/python3/ZhihuSpider/login/login.py", line 151, in do_login
    login_json = json.loads(login_page.text.encode('latin-1').decode('unicode-escape'))
  File "/usr/local/python3/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
None
?? /home/python3/ZhihuSpider/captcha.jpg ????captcha.jpg ????
??????

**Comment by kong36088** [comment]
知乎关了http的接口，全部改用https的接口，导致接口调用失败。现BUG已修复，可以使用邮箱帐号登陆
