### ISSUE TITLE
设置为UTF8 解码器仍旧会使用GBK

### ISSUE THREAD

**Issue by SpriggyDesmond** [kong36088/ZhihuSpider#5]
Windows Server 2012
Python 3.5

```
Traceback (most recent call last):
  File "get_user.py", line 357, in get_user_info
    print(replace_data)
UnicodeEncodeError: 'gbk' codec can't encode character '\u2022' in position 171:
 illegal multibyte sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python35\lib\threading.py", line 923, in _bootstrap_inner
    self.run()
  File "get_user.py", line 398, in run
    self.entrance()
  File "get_user.py", line 389, in entrance
    self.get_user_info(name_url)
  File "get_user.py", line 364, in get_user_info
    print(user_info)
UnicodeEncodeError: 'gbk' codec can't encode character '\u2022' in position 1077
: illegal multibyte sequence
```

**Comment by SpriggyDesmond** [comment]
当然注释掉357行的print(replace_data)就OK了

**Comment by kong36088** [comment]
本人还未在windows平台下测试过编码相关问题，同时也不建议使用windows进行数据抓取哈。可以使用readme中提供的docker容器进行环境模拟。
后续我会针对这一问题进行测试，同时也欢迎提PR~

**Comment by kong36088** [comment]
经测试，在windows下python3.6没有发现此类问题，请检查您的python编码设置以及命令行编码格式是否存在问题
